const fs = require('fs');
const vm = require('vm');
const path = require('path');
function load() {
 const file=path.resolve(__dirname,'../../../public/scripts/order-obat.js');
 const code=fs.existsSync(file)?fs.readFileSync(file,'utf8').replace(/^import .*;$/gm,'').replace(/export /g,''):'';
 const ctx={crypto:{randomUUID:()=> 'request-1'},escapeHtml:s=>String(s??'').replaceAll('<','&lt;').replaceAll('>','&gt;'),Map,console};
 vm.createContext(ctx); vm.runInContext(code+';this.Controller=typeof OrderController === "undefined" ? undefined : OrderController;',ctx); return ctx.Controller;
}
const item=(id,priority='urgent')=>({obat_id:id,name:'Obat',supplier_id:1,priority,recommended_quantity:12,analysis_fingerprint:'old'});
function setup(api=async()=>({items:[],suppliers:[]})) {const C=load(); expect(typeof C).toBe('function'); return new C(api);}
test('bulk selection excludes manual review while deliberate selection permits it',()=>{const c=setup();c.items=[item(1),item(2,'manual'),item(3,'enough')];c.selectUrgent();expect([...c.selection.keys()]).toEqual(['1']);c.select(2,true);expect(c.selection.has('2')).toBe(true);});
test('refresh failure retains quantity and selected evidence',async()=>{const c=setup(async()=>{throw Error('offline')});c.items=[item(1)];c.select(1,true);c.selection.get('1').quantity=42;await expect(c.refresh()).rejects.toThrow('offline');expect(c.selection.get('1').quantity).toBe(42);});
test('failed save retries identical request key and suppresses simultaneous saves',async()=>{let release;const requests=[];const c=setup((url,opts)=>{requests.push(opts.body);return new Promise((resolve,reject)=>{release=()=>reject(Error('offline'))})});c.items=[item(1)];c.select(1,true);const p=c.save();await c.save();expect(requests).toHaveLength(1);release();await expect(p).rejects.toThrow('offline');const q=c.save();release();await expect(q).rejects.toThrow('offline');expect(requests[0].request_key).toBe(requests[1].request_key);});
test('changed analysis preserves chosen quantity and requires explicit retry',async()=>{const c=setup(async()=>{const e=Error('changed');e.code='ANALYSIS_CHANGED';e.data={items:[{...item(1),analysis_fingerprint:'fresh',recommended_quantity:99}]};throw e});c.items=[item(1)];c.select(1,true);c.selection.get('1').quantity=7;await expect(c.save()).rejects.toThrow('changed');expect(c.selection.get('1').quantity).toBe(7);expect(c.selection.get('1').analysis_fingerprint).toBe('fresh');expect(c.analysisChanged).toBe(true);});
test('supplier refresh changes only selected item evidence and preserves quantity',async()=>{const c=setup(async url=>{expect(url).toContain('supplier_id=2');return {items:[{...item(1),supplier_id:2,analysis_fingerprint:'supplier2'}]}});c.items=[item(1)];c.select(1,true);c.selection.get('1').quantity=7;await c.setSupplier(1,2);expect(c.selection.get('1')).toMatchObject({quantity:7,supplier_id:2,analysis_fingerprint:'supplier2'});});
test('invalid quantity or missing supplier never reaches draft API',async()=>{const api=jest.fn();const c=setup(api);c.items=[item(1)];c.select(1,true);c.selection.get('1').quantity=0;await expect(c.save()).rejects.toThrow('positif');expect(api).not.toHaveBeenCalled();c.selection.get('1').quantity=1;c.selection.get('1').supplier_id=null;await expect(c.save()).rejects.toThrow('supplier');expect(api).not.toHaveBeenCalled();});
test('supplier refresh failure preserves original supplier and fingerprint',async()=>{const c=setup(async()=>{throw Error('offline')});c.items=[item(1)];c.select(1,true);await expect(c.setSupplier(1,2)).rejects.toThrow('offline');expect(c.selection.get('1')).toMatchObject({supplier_id:1,analysis_fingerprint:'old'});});
test('refresh success preserves selected snapshot until save revalidation',async()=>{const c=setup(async()=>({items:[{...item(1),recommended_quantity:50,analysis_fingerprint:'new'}],suppliers:[]}));c.items=[item(1)];c.select(1,true);await c.refresh();expect(c.selection.get('1')).toMatchObject({quantity:12,analysis_fingerprint:'old'});expect(c.items[0].analysis_fingerprint).toBe('new');});
test('operation lock restores preexisting disabled controls',()=>{
 const file=path.resolve(__dirname,'../../../public/scripts/order-obat.js');const code=fs.readFileSync(file,'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'');
 const ctx={escapeHtml:String};vm.createContext(ctx);vm.runInContext(code+';this.lock=typeof lockControls === "undefined"?undefined:lockControls;',ctx);
 expect(typeof ctx.lock).toBe('function');const controls=[{disabled:false},{disabled:true}];const restore=ctx.lock({querySelectorAll:()=>controls});expect(controls.map(c=>c.disabled)).toEqual([true,true]);restore();expect(controls.map(c=>c.disabled)).toEqual([false,true]);
});
test('removing a draft item preserves retained quantity and evidence and rejects empty draft',()=>{
 const file=path.resolve(__dirname,'../../../public/scripts/order-obat.js');const code=fs.readFileSync(file,'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'');const ctx={escapeHtml:String};vm.createContext(ctx);vm.runInContext(code+';this.remove=typeof removeDraftItem === "undefined"?undefined:removeDraftItem;',ctx);
 expect(typeof ctx.remove).toBe('function');const kept={obat_id:2,quantity:19,analysis:{analysis_fingerprint:'retained'}};const draft={status:'draft',items:[{obat_id:1,quantity:2},kept]};ctx.remove(draft,1);expect(draft.items).toEqual([kept]);expect(()=>ctx.remove(draft,2)).toThrow('satu');expect(draft.items).toEqual([kept]);
});
test('successful create immediately adds duplicate warning reference before any refresh',async()=>{const c=setup(async()=>({drafts:[{id:'d-1',supplier_id:1}],replayed:false}));c.items=[item(1)];c.select(1,true);await c.save();expect(c.items[0].active_drafts).toEqual([{id:'d-1',supplier_id:1}]);expect(c.selection.size).toBe(0);});
test('archiving removes only matching draft warning from items and retained selections',()=>{const c=setup();c.items=[{...item(1),active_drafts:[{id:'d-1',supplier_id:1},{id:'d-2',supplier_id:1}]}];c.select(1,true);expect(typeof c.removeDraftReference).toBe('function');c.removeDraftReference('d-1');expect(c.items[0].active_drafts).toEqual([{id:'d-2',supplier_id:1}]);expect(c.selection.get('1').active_drafts).toEqual([{id:'d-2',supplier_id:1}]);});
