CREATE TABLE IF NOT EXISTS docboard_gambiran_resumes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  facility VARCHAR(32) NOT NULL DEFAULT 'gambiran',
  mr_digits VARCHAR(32) NOT NULL,
  mr_display VARCHAR(64) NOT NULL,
  patient_name VARCHAR(255) NULL,
  archive_version INT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  first_visit_at DATETIME NULL,
  last_visit_at DATETIME NULL,
  case_count INT UNSIGNED NOT NULL DEFAULT 0,
  event_count INT UNSIGNED NOT NULL DEFAULT 0,
  file_count INT UNSIGNED NOT NULL DEFAULT 0,
  jpg_count INT UNSIGNED NOT NULL DEFAULT 0,
  warnings_json JSON NULL,
  snapshot_r2_key VARCHAR(512) NULL,
  manifest_r2_key VARCHAR(512) NULL,
  resume_txt_r2_key VARCHAR(512) NULL,
  resume_docx_r2_key VARCHAR(512) NULL,
  r2_bucket VARCHAR(128) NULL,
  last_error TEXT NULL,
  created_by VARCHAR(64) NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_docboard_gambiran_resume_version (facility, mr_digits, archive_version),
  KEY idx_docboard_gambiran_resume_patient (mr_digits, patient_name),
  KEY idx_docboard_gambiran_resume_status (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS docboard_gambiran_resume_files (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  resume_id BIGINT UNSIGNED NOT NULL,
  source_file_id VARCHAR(255) NULL,
  case_id VARCHAR(64) NULL,
  category VARCHAR(64) NULL,
  occurred_at DATETIME NULL,
  filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(128) NOT NULL,
  byte_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sha256 CHAR(64) NOT NULL,
  original_r2_key VARCHAR(512) NOT NULL,
  jpg_keys_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_docboard_gambiran_resume_file
    FOREIGN KEY (resume_id) REFERENCES docboard_gambiran_resumes(id) ON DELETE CASCADE,
  KEY idx_docboard_gambiran_resume_file (resume_id, category, occurred_at),
  KEY idx_docboard_gambiran_resume_case (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
