CREATE TABLE IF NOT EXISTS docboard_morbid_cases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  operation_data_id BIGINT UNSIGNED NOT NULL,
  facility VARCHAR(32) NOT NULL DEFAULT 'gambiran',
  case_id VARCHAR(32) NOT NULL,
  mr_id VARCHAR(64) NULL,
  patient_name VARCHAR(255) NOT NULL,
  diagnosis TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'collecting',
  snapshot_version INT UNSIGNED NOT NULL DEFAULT 1,
  snapshot_r2_key VARCHAR(512) NOT NULL,
  snapshot_r2_bucket VARCHAR(128) NULL,
  cppt_count INT UNSIGNED NOT NULL DEFAULT 0,
  penunjang_result_count INT UNSIGNED NOT NULL DEFAULT 0,
  penunjang_file_count INT UNSIGNED NOT NULL DEFAULT 0,
  operation_count INT UNSIGNED NOT NULL DEFAULT 0,
  prescription_count INT UNSIGNED NOT NULL DEFAULT 0,
  collected_at DATETIME NULL,
  last_error TEXT NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_docboard_morbid_case (facility, case_id),
  KEY idx_docboard_morbid_operation (operation_data_id),
  KEY idx_docboard_morbid_patient (mr_id, patient_name),
  KEY idx_docboard_morbid_status (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
