/**
 * CDN & Static Asset Configuration
 * Defines cache policy tiers and asset fingerprinting helpers.
 *
 * Cache tiers:
 *   immutable  — versioned JS/CSS/fonts  → 1 year, immutable
 *   static     — images, media           → 30 days
 *   short      — HTML, service worker    → no-cache / 5 min
 *   api        — API JSON responses      → private, short-lived
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Cache policy tiers
// ---------------------------------------------------------------------------

const CACHE_TIERS = {
    immutable: {
        'Cache-Control': 'public, max-age=31536000, immutable',
        extensions: ['.js', '.css', '.woff2', '.woff', '.ttf', '.eot'],
    },
    static: {
        'Cache-Control': 'public, max-age=2592000',
        extensions: ['.png', '.jpg', '.jpeg', '.svg', '.webp', '.ico', '.gif', '.mp4', '.pdf'],
    },
    short: {
        'Cache-Control': 'no-cache, must-revalidate',
        extensions: ['.html'],
    },
};

/**
 * Determine cache tier for a file path.
 * Returns the tier name or null if no match.
 */
function getCacheTier(filePath) {
    const ext = path.extname(filePath).toLowerCase();
    for (const [tier, def] of Object.entries(CACHE_TIERS)) {
        if (def.extensions.includes(ext)) return tier;
    }
    return null;
}

/**
 * Return Cache-Control header value for a given file path.
 */
function getCacheControl(filePath) {
    const tier = getCacheTier(filePath);
    if (!tier) return 'public, max-age=3600'; // default 1h
    return CACHE_TIERS[tier]['Cache-Control'];
}

// ---------------------------------------------------------------------------
// Asset fingerprinting — content-hash for cache-busting
// ---------------------------------------------------------------------------

const _hashCache = new Map();

/**
 * Compute a short content hash (8 hex chars) for a file.
 * Result is memoized for the lifetime of the process.
 */
function fileHash(absolutePath) {
    if (_hashCache.has(absolutePath)) return _hashCache.get(absolutePath);
    try {
        const content = fs.readFileSync(absolutePath);
        const hash = crypto.createHash('md5').update(content).digest('hex').slice(0, 8);
        _hashCache.set(absolutePath, hash);
        return hash;
    } catch {
        return '00000000';
    }
}

/**
 * Build a versioned URL: /scripts/main.js → /scripts/main.js?v=a1b2c3d4
 */
function versionedUrl(publicRelPath, publicDir) {
    const abs = path.join(publicDir, publicRelPath);
    return `${publicRelPath}?v=${fileHash(abs)}`;
}

/**
 * Invalidate the in-memory hash cache (e.g. after deploy).
 */
function purgeHashCache() {
    _hashCache.clear();
}

// ---------------------------------------------------------------------------
// Nginx snippet generator — produces a text block you can paste into your
// nginx server {} block. This is NOT auto-applied; it's a helper for the
// deploy/config workflow.
// ---------------------------------------------------------------------------

function generateNginxCacheSnippet() {
    return `
# --- CDN & Static Cache Policy (generated by cdn.js) ---

# Immutable versioned assets (JS, CSS, fonts) — 1 year
location ~* \\.(js|css|woff2?|ttf|eot)$ {
    expires 365d;
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header X-Cache-Tier "immutable";
    access_log off;
}

# Static media — 30 days
location ~* \\.(png|jpe?g|svg|webp|ico|gif|mp4|pdf)$ {
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
    add_header X-Cache-Tier "static";
    access_log off;
}

# HTML pages — no-cache (always revalidate)
location ~* \\.html$ {
    add_header Cache-Control "no-cache, must-revalidate";
    add_header X-Cache-Tier "short";
}

# Service worker — never cache
location = /sw.js {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    expires -1;
}

# API responses — private, short-lived
location /api/ {
    add_header Cache-Control "private, no-cache";
    add_header X-Cache-Tier "api";
}

# --- End CDN & Static Cache Policy ---
`.trim();
}

module.exports = {
    CACHE_TIERS,
    getCacheTier,
    getCacheControl,
    fileHash,
    versionedUrl,
    purgeHashCache,
    generateNginxCacheSnippet,
};
